# Generated by Django 4.2.2 on 2023-06-29 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="顾客姓名")),
                ("age", models.IntegerField(verbose_name="顾客年龄")),
                ("birthday", models.DateField(verbose_name="顾客生日")),
                ("phonenumber", models.CharField(max_length=32, verbose_name="顾客联系方式")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="顾客性别"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.date(1900, 1, 1),
                        null=True,
                        verbose_name="注册时间",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="员工姓名")),
                ("age", models.IntegerField(verbose_name="员工年龄")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                ("phonenumber", models.CharField(max_length=32, verbose_name="员工联系方式")),
                ("create_time", models.DateField(verbose_name="入职时间")),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "identify",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cake.staff",
                        verbose_name="所属员工",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orderform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starttime", models.DateTimeField(verbose_name="订单产生时间")),
                (
                    "endtime",
                    models.DateTimeField(
                        blank=True, default=None, verbose_name="订单结束时间"
                    ),
                ),
                ("amount", models.FloatField(verbose_name="订单金额")),
                ("commodity", models.CharField(max_length=128, verbose_name="商品名字")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "已下单"),
                            (2, "制作中"),
                            (3, "已完成"),
                            (4, "推迟"),
                            (4, "取消"),
                        ],
                        default=1,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cake.customer",
                        verbose_name="顾客信息",
                    ),
                ),
            ],
        ),
    ]
