# Generated by Django 4.2.2 on 2023-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cake", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderform",
            name="endtime",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="订单结束时间"
            ),
        ),
    ]
