# Generated by Django 4.2.2 on 2023-06-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cake", "0002_alter_orderform_endtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderform",
            name="presettime",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="订单预定完成时间"
            ),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="endtime",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="订单实际结束时间"
            ),
        ),
    ]
