# Generated by Django 4.2.2 on 2023-07-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cake", "0003_orderform_presettime_alter_orderform_endtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="商品名字")),
                ("serialnumber", models.CharField(max_length=128, verbose_name="商品编号")),
                ("count", models.IntegerField(default=0, verbose_name="商品库存数量")),
            ],
        ),
    ]
