# Generated by Django 4.2.2 on 2023-07-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cake", "0004_goods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goods",
            name="count",
        ),
    ]
